### ISSUE TITLE
create-session: Inappropriate file type or format

### ISSUE THREAD

**Issue by Pyrohh** [martanne/abduco#13]
I'm experiencing this on OpenBSD.

The error message in the title is happening because `chmod(2)` is returning `EFTYPE` at `server.c:57`:

    if (r == -1 || chmod(sockaddr.sun_path, S_ISVTX|S_IRUSR|S_IWUSR) == -1) {
            close(fd);
            return -1;
    }

This is because the sticky bit (`S_ISVTX`) is being set on a non-directory; removing the use of `S_ISVTX` avoids the issue and abduco functions normally.

According to both [`sticky(8)`][sticky] and [`chmod(2)`][chmod] on OpenBSD, doing this shouldn't be an issue, i.e., it's ignored, but that's evidently not the case given `EFTYPE` is returned. I assume you use Linux, where setting the sticky bit on sockets is actually ignored, at least according to [the Wikipedia page](https://en.wikipedia.org/wiki/Sticky_bit#Usage).

Anyway, does it even make sense to set the sticky bit on `sockaddr.sun_path`, given it's apparently ignored? Did you mean to set it on `dirname(sockaddr.sun_path)` instead?

[chmod]: http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/chmod.2?query=chmod&sec=2
[sticky]: http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man8/sticky.8?query=sticky

**Comment by martanne** [comment]
The reason why it is set on the file/socket is because the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) (search for "sticky") states that such files are ignored by periodic cleanup procedures. The spec uses the sticky bit as a "tag" for the file which is otherwise ignored.

I don't think this is even used in practice, I therefore suggest to revert 15ae398ea51f9adb282d7cf93a998a8ea401fd21. Does this fix your issue?

Does it otherwise work on OpenBSD?

**Comment by Pyrohh** [comment]
> I don't think this is even used in practice, I therefore suggest to revert 15ae398. Does this fix your issue?

Yes

> Does it otherwise work on OpenBSD?

Indeed, thanks a lot for your help.
