### ISSUE TITLE
acknowledge parts of the code come from dtach

### ISSUE THREAD

**Issue by anarcat** [martanne/abduco#20]
There is an interesting comparative analysis of dtach and abduco in the Debian [bug #771102](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771102). In it, the dtach author makes a convincing argument that significant parts of abduco have been copied verbatim from dtach.

dtach is licensed under GPLv2, while abduco is licensed under ISC. If it is indeed the case that parts of dtach have been imported then rewritten in abduco, the license of abduco should recognize that, and should also be licensed under a GPLv2-compatible license.

this problem has led to abduco's removal from Debian, and its lack of updates in Ubuntu, and will prevent it from entering Debian again. I tried to update abduco myself in Debian, and was faced with similar license problems, in [bug #833897](https://bugs.debian.org/833897).

**Comment by aparaatti** [comment]
Can one license parts of code differently? E.g. if there are some lines that "resemble too much" dtach, could these parts be GPLv2:ed and then other parts be kept ISC...

**Comment by anarcat** [comment]
No. I believe the legal consensus is that a license applies to a whole file and thta if a GPL snippet is imported in another file, that other file becomes GPL.

I am not a lawyer, however, so this is not legal advice.

Furthermore, it's not just a matter of legalities but giving credit where it is due. It seems to me dishonest to present abduco as a cleanroom implementation if it reuses significant part of the original dtach code.

**Comment by martanne** [comment]
There are specific reasons why some portions of the code are similar. The initial abduco versions tried to remain compatible with dtach by using the same "wire" protocol. The terminal setup routines used by both tools are given as examples in manual pages and probably not copyrightable in the first place. I agree that abduco was somewhat inspired by dtach and mainly created because of implementation concerns of the latter.  However, I certainly disagree with the claim that "significant parts of abduco have been copied verbatim from dtach". And yes, I should reply to the Debian bug presenting my point of view. In fact I wanted to do that a long time ago, but free time is scarce and I end up doing more interesting things ...

**Comment by lanodan** [comment]
> both tools are given as examples in manual pages
Source ?

**Comment by martanne** [comment]
@lanodan I'm not sure how to interpret your selective quote, the original context was:

> The terminal setup routines used by both tools are given as examples in manual pages and probably not copyrightable in the first place.

I was referring to the code similarities for enabling raw mode which is listed in [`termios(3)`](http://man7.org/linux/man-pages/man3/termios.3.html) and equivalent to a call to the non standard `cfmakeraw(3)` function.

**Comment by martanne** [comment]
One issue (see #27) is enough for this.
