### ISSUE TITLE
remote connection with local socket

### ISSUE THREAD

**Issue by grafoo** [martanne/abduco#25]
first of all i really appreciate the effort you are putting into this.
so far abduco works as expected and isn't eating away cpu time on my arm board like tmux does.

back to the issue...
is there a way to  "export" the local unix socket via tcp (with e.g. socat)?
i know this does not work well with tmux because it's using file descriptor passing, but how is the story here with abduco?

`(abduco -n arm-box) <= unix-socket <--local--> tcp-socket <==remote==> tcp-socket <--local--> unix-socket => (abduco -a remote-arm-box)`

maybe i did not use socat properly but the above hack was not working.

cheers, grafoo

**Comment by martanne** [comment]
What do you want to achieve? The traditional setup I often use is to simply ssh to your remote machine. It would "look" more like the following:

```
abduco -n arm-box <- unix socket local -> abduco -a arm-box <--> sshd <= tcp socket remote => ssh
```

If for whatever reason you want to run the two abduco instances (client and server) on two different machines, then [socket forwarding](https://lwn.net/Articles/609321/) as supported by recent OpenSSH versions is probably a better idea than plain socat.

However, due to the current implementation (raw structs are transferred over the unix socket) this can only work between machines of the same architecture, bitness and endianness.

So in general this is currently not supported and probably a bad idea.

**Comment by grafoo** [comment]
having the ability to e.g. copy/paste between different hosts without relying on the terminal to do so (which gets annoying if there are lots of split panes) is the major thing i'd like to achieve with the socket forwarding.

didn't know that openssh also supports socket forwarding since v6.7. this is awesome!

thanks for the warning but i'll give it a try anyway... this is too tempting.

btw: results from a first test run between two x64 hosts are promising :)
