### ISSUE TITLE
Can't compile on OpenBSD

### ISSUE THREAD

**Issue by greduan** [martanne/abduco#4]
I'm switching to OpenBSD from Linux (CRUX), so sorry if this seems a little bit ignorant. When I run `make` I get several errors:

http://sprunge.us/HKgH

I was able to compile it successfully just a couple days ago on Linux which makes me believe it doesn't work because I'm on OpenBSD.

Is this something you can fix or is it something for me to fix on my end? BTW I'm on OpenBSD 5.6 (not -current).

**Comment by martanne** [comment]
Well it is expected that you tweak `config.mk` to match your system (the defaults are for Linux). You should thus check your system header files and/or man pages and see which feature test macros are necessary. Then do something like the following (untested):

`make CPPFLAGS=-D_BSD_SOURCE`

I hope this is enough information for you to fix it by yourself, otherwise I will have to start up my OpenBSD system ...

**Comment by greduan** [comment]
Nope that's good enough. Thanks man! :)

**Comment by Jaso-N7** [comment]
That definitely worked for me as well. Configured and built it on OpenBSD 5.9.
